create table "public"."project_details" (
    "id" bigint generated by default as identity not null,
    "project_uuid" uuid not null,
    "settings" jsonb not null,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."project_details" enable row level security;

CREATE UNIQUE INDEX project_details_pkey ON public.project_details USING btree (id);

alter table "public"."project_details" add constraint "project_details_pkey" PRIMARY KEY using index "project_details_pkey";

grant delete on table "public"."project_details" to "anon";

grant insert on table "public"."project_details" to "anon";

grant references on table "public"."project_details" to "anon";

grant select on table "public"."project_details" to "anon";

grant trigger on table "public"."project_details" to "anon";

grant truncate on table "public"."project_details" to "anon";

grant update on table "public"."project_details" to "anon";

grant delete on table "public"."project_details" to "authenticated";

grant insert on table "public"."project_details" to "authenticated";

grant references on table "public"."project_details" to "authenticated";

grant select on table "public"."project_details" to "authenticated";

grant trigger on table "public"."project_details" to "authenticated";

grant truncate on table "public"."project_details" to "authenticated";

grant update on table "public"."project_details" to "authenticated";

grant delete on table "public"."project_details" to "service_role";

grant insert on table "public"."project_details" to "service_role";

grant references on table "public"."project_details" to "service_role";

grant select on table "public"."project_details" to "service_role";

grant trigger on table "public"."project_details" to "service_role";

grant truncate on table "public"."project_details" to "service_role";

grant update on table "public"."project_details" to "service_role";


