create type "public"."enum_messages_sender" as enum ('project', 'user');

create table "public"."chats" (
    "id" bigint generated by default as identity not null,
    "project_uuid" uuid not null,
    "user_id" uuid not null,
    "created_at" timestamp with time zone not null default now(),
    "disabled_at" timestamp with time zone,
    "thread_ts" text
);


alter table "public"."chats" enable row level security;

create table "public"."messages" (
    "id" bigint generated by default as identity not null,
    "chat_id" bigint not null,
    "sender" enum_messages_sender not null,
    "text" text not null,
    "created_at" timestamp with time zone not null default now(),
    "project_uuid" uuid not null
);


alter table "public"."messages" enable row level security;

create table "public"."projects" (
    "id" bigint generated by default as identity not null,
    "uuid" uuid not null default gen_random_uuid(),
    "access_token" text not null,
    "team_id" text not null,
    "team_name" text not null,
    "channel_id" text not null,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."projects" enable row level security;

CREATE UNIQUE INDEX chats_pkey ON public.chats USING btree (id);

CREATE UNIQUE INDEX chats_project_uuid_user_id_disabled_at_idx ON public.chats USING btree (project_uuid, user_id, disabled_at);

CREATE UNIQUE INDEX messages_pkey ON public.messages USING btree (id);

CREATE UNIQUE INDEX projects_pkey ON public.projects USING btree (id);

CREATE UNIQUE INDEX projects_team_id_key ON public.projects USING btree (team_id);

CREATE UNIQUE INDEX projects_uuid_key ON public.projects USING btree (uuid);

alter table "public"."chats" add constraint "chats_pkey" PRIMARY KEY using index "chats_pkey";

alter table "public"."messages" add constraint "messages_pkey" PRIMARY KEY using index "messages_pkey";

alter table "public"."projects" add constraint "projects_pkey" PRIMARY KEY using index "projects_pkey";

alter table "public"."chats" add constraint "chats_project_uuid_fkey" FOREIGN KEY (project_uuid) REFERENCES projects(uuid) not valid;

alter table "public"."chats" validate constraint "chats_project_uuid_fkey";

alter table "public"."chats" add constraint "chats_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) not valid;

alter table "public"."chats" validate constraint "chats_user_id_fkey";

alter table "public"."messages" add constraint "messages_chat_id_fkey" FOREIGN KEY (chat_id) REFERENCES chats(id) not valid;

alter table "public"."messages" validate constraint "messages_chat_id_fkey";

alter table "public"."messages" add constraint "messages_proejct_uuid_fkey" FOREIGN KEY (project_uuid) REFERENCES projects(uuid) not valid;

alter table "public"."messages" validate constraint "messages_proejct_uuid_fkey";

alter table "public"."projects" add constraint "projects_team_id_key" UNIQUE using index "projects_team_id_key";

alter table "public"."projects" add constraint "projects_uuid_key" UNIQUE using index "projects_uuid_key";

grant delete on table "public"."chats" to "anon";

grant insert on table "public"."chats" to "anon";

grant references on table "public"."chats" to "anon";

grant select on table "public"."chats" to "anon";

grant trigger on table "public"."chats" to "anon";

grant truncate on table "public"."chats" to "anon";

grant update on table "public"."chats" to "anon";

grant delete on table "public"."chats" to "authenticated";

grant insert on table "public"."chats" to "authenticated";

grant references on table "public"."chats" to "authenticated";

grant select on table "public"."chats" to "authenticated";

grant trigger on table "public"."chats" to "authenticated";

grant truncate on table "public"."chats" to "authenticated";

grant update on table "public"."chats" to "authenticated";

grant delete on table "public"."chats" to "service_role";

grant insert on table "public"."chats" to "service_role";

grant references on table "public"."chats" to "service_role";

grant select on table "public"."chats" to "service_role";

grant trigger on table "public"."chats" to "service_role";

grant truncate on table "public"."chats" to "service_role";

grant update on table "public"."chats" to "service_role";

grant delete on table "public"."messages" to "anon";

grant insert on table "public"."messages" to "anon";

grant references on table "public"."messages" to "anon";

grant select on table "public"."messages" to "anon";

grant trigger on table "public"."messages" to "anon";

grant truncate on table "public"."messages" to "anon";

grant update on table "public"."messages" to "anon";

grant delete on table "public"."messages" to "authenticated";

grant insert on table "public"."messages" to "authenticated";

grant references on table "public"."messages" to "authenticated";

grant select on table "public"."messages" to "authenticated";

grant trigger on table "public"."messages" to "authenticated";

grant truncate on table "public"."messages" to "authenticated";

grant update on table "public"."messages" to "authenticated";

grant delete on table "public"."messages" to "service_role";

grant insert on table "public"."messages" to "service_role";

grant references on table "public"."messages" to "service_role";

grant select on table "public"."messages" to "service_role";

grant trigger on table "public"."messages" to "service_role";

grant truncate on table "public"."messages" to "service_role";

grant update on table "public"."messages" to "service_role";

grant delete on table "public"."projects" to "anon";

grant insert on table "public"."projects" to "anon";

grant references on table "public"."projects" to "anon";

grant select on table "public"."projects" to "anon";

grant trigger on table "public"."projects" to "anon";

grant truncate on table "public"."projects" to "anon";

grant update on table "public"."projects" to "anon";

grant delete on table "public"."projects" to "authenticated";

grant insert on table "public"."projects" to "authenticated";

grant references on table "public"."projects" to "authenticated";

grant select on table "public"."projects" to "authenticated";

grant trigger on table "public"."projects" to "authenticated";

grant truncate on table "public"."projects" to "authenticated";

grant update on table "public"."projects" to "authenticated";

grant delete on table "public"."projects" to "service_role";

grant insert on table "public"."projects" to "service_role";

grant references on table "public"."projects" to "service_role";

grant select on table "public"."projects" to "service_role";

grant trigger on table "public"."projects" to "service_role";

grant truncate on table "public"."projects" to "service_role";

grant update on table "public"."projects" to "service_role";

create policy "chats_select"
on "public"."chats"
as permissive
for select
to authenticated
using (((user_id = auth.uid()) AND (disabled_at IS NULL)));


create policy "messages_select"
on "public"."messages"
as permissive
for select
to authenticated
using ((EXISTS ( SELECT 1
   FROM chats
  WHERE (chats.id = messages.chat_id))));



